### ISSUE TITLE
Crashing on start up with gems 284 and lib 136

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/SGExtraParts#10]
### Versions

Minecraft Version: 1.12.2
Extra Parts Version: 1.4.1.34
Silent's Gems Version: 2.7.9-284
Silent Lib Version: 2.3.16-136

### Expected behavior

- probably should load.

### Actual behaviour

- blows up.

### Steps to reproduce the problem

just load it.

heres the crash.

[crash-2018-08-11_16.57.50-client.txt](https://github.com/SilentChaos512/SGExtraParts/files/2279991/crash-2018-08-11_16.57.50-client.txt)

**Comment by SilentChaos512** [comment]
Closed by 83341f35b43f8cd1a132d1d38395a13e1cd4c8d9. Version 1.4.2 should be available to download soon, just waiting for approval.

**Comment by Darkmega18** [comment]
Roger. So should be alright now. :D
