### ISSUE TITLE
Item creative bug

### ISSUE THREAD

**Issue by M6444** [SilentChaos512/SGExtraParts#11]
when I am in creative, there is a strange bug where some of the items are in tabs they should not be in, even in other mod tabs, and for some reason the item Feldspar is in the delete item section in the creative inventory, I dont think it cause any real issue just weird to see them there 

![2018-08-30_22 02 34](https://user-images.githubusercontent.com/42199213/44893738-46a91b80-aca1-11e8-9999-2a6f8bbe4ed1.png)

![2018-08-30_22 02 26](https://user-images.githubusercontent.com/42199213/44893721-385aff80-aca1-11e8-87cc-6626935b650a.png)

### Versions

Minecraft Version: 1.12.2
Extra Parts Version: 1.4.3-40
Silent's Gems Version: 2.8.2-293
Silent Lib Version: 3.0.1-145

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
Ah, right, I always forget about the greatest change vanilla Minecraft ever made. Items have to manually check the creative tab in 1.12.2...
