### ISSUE TITLE
Parts not rendering

### ISSUE THREAD

**Issue by darklordwonton** [SilentChaos512/SGExtraParts#2]
When I make a tool with a material added by this mod the parts don't render.

**Comment by SilentChaos512** [comment]
Any particular types of tools that seem to be affected?

**Comment by darklordwonton** [comment]
Seems to be every tool. Here's a reddit thread from someone with a similar problem: https://www.reddit.com/r/feedthebeast/comments/565ory/i_am_wielding_a_third_of_a_diamond_pickaxe/

**Comment by SilentChaos512** [comment]
Thanks for reporting this, I'll have it fixed sometime tomorrow.
