### ISSUE TITLE
Minecraft crash with sgextraparts

### ISSUE THREAD

**Issue by T2Bmc** [SilentChaos512/SGExtraParts#3]
Hello, I've been trying to troubleshoot this for over two hours now and the only thing I've
figured out is that sgextraparts is the cause, how or why I don't know.

I tried with only Silent lib and Silent's gems installed and I still get the same crash.
I also tried with the latest version of forge 13.20.0.2255 and the same crash still happens.
I'm not a programmer so the problem may be really simple.

Crash log is here: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.6.26 mc1.11.2.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  ItemPatchingLoader (ItemPhysic Full 1.3.11 mc1.11.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 3/13/17 12:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Silent's Gems: Extra Parts (sgextraparts)
Caused by: java.lang.NoSuchFieldError: materials
	at net.silentchaos512.sgextraparts.item.ModItems.init(ModItems.java:16)
	at net.silentchaos512.sgextraparts.SGExtraParts.preInit(SGExtraParts.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1657555480 bytes (1580 MB) / 2772959232 bytes (2644 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2233 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2233.jar) 
	UCH	forge{13.20.0.2233} [Minecraft Forge] (forge-1.11.2-13.20.0.2233.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCH	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCH	dmonsters{1.15} [Deadly Monsters] (1.11.2_deadly_monsters_1.15.jar) 
	UCH	jei{4.2.9.247} [Just Enough Items] (jei_1.11.2-4.2.9.247.jar) 
	UCH	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCH	actuallyadditions{1.11.2-r103} [Actually Additions] (ActuallyAdditions-1.11.2-r103.jar) 
	UCH	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCH	advinv{1.3.0} [Advanced Inventory] (advInv-1.11.2-1.3.0.jar) 
	UCH	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCH	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCH	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCH	thedragonlib{1.11.2-3.1.1} [TheDragonLib] (thedragonlib-1.11.2-3.1.1.jar) 
	UCH	armorplus{1.11.2-10.1.2.3} [ArmorPlus] (armorplus-1.11.2-10.1.2.3.jar) 
	UCH	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCH	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCH	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.0.233+4d933ac.jar) 
	UCH	biomesoplenty{6.0.2.2167} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2167-universal.jar) 
	UCH	silentlib{2.0.3} [Silent Lib] (SilentLib-1.11.x-2.0.3-43.jar) 
	UCH	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCH	silentgems{2.3.1} [Silent's Gems] (SilentsGems-1.11.x-2.3.1-140.jar) 
	UCH	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UCH	bloodmagic{1.11-2.1.6-75} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.6-75.jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCH	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCH	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCH	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCH	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.6.26 mc1.11.2.jar) 
	UCH	cyclopscore{0.9.4} [Cyclops Core] (CyclopsCore-1.11.2-0.9.4.jar) 
	UCH	forestry{5.3.2.58} [Forestry] (forestry_1.11.2-5.3.2.58.jar) 
	UCH	eleccore{1.7.9999.custom} [ElecCore] (ElecCore-1.11-1.7.402.jar) 
	UCH	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCH	shetiphiancore{3.4.3} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.3.jar) 
	UCH	endertanks{1.5.3} [EnderTanks] (endertanks-1.11.0-1.5.3.jar) 
	UCH	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.0.12 mc1.11.2.jar) 
	UCH	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCH	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCH	evilcraft{0.10.21} [EvilCraft] (EvilCraft-1.11.2-0.10.21.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCH	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCH	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCH	hardcoredarkness{1.8.1} [Hardcore Darkness] (HardcoreDarkness-MC1.11-1.8.1.jar) 
	UCH	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCH	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCH	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCH	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCH	lightningcraft{2.8.2} [LightningCraft] (lightningcraft-2.8.2-[1.11.2].jar) 
	UCH	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCH	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCH	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCH	minecolonies{1.11-0.6.3113} [MineColonies] (minecolonies-universal-1.11-0.6.3113.jar) 
	UCH	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCH	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCH	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.3.3 mc1.11.2.zip) 
	UCH	harvestcraft{1.11.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2f.jar) 
	UCH	rftools{5.87} [RFTools] (rftools-1.1x-5.87.jar) 
	UCH	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UCH	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCH	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
	UCH	randomthings{3.8} [Random Things] (RandomThings-MC1.11.2-3.8.jar) 
	UCH	reborncore{2.13.4.37} [RebornCore] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCH	reborncore-mcmultipart{2.13.4.37} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCH	reccomplex{1.2.9.1} [Recurrent Complex] (RecurrentComplex-1.2.9.1.jar) 
	UCH	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCH	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCH	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCH	roguelike{1.6.5} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.5.jar) 
	UCH	roots{0.012} [Roots 2] (roots-2-0.012.jar) 
	UCE	sgextraparts{1.2.4} [Silent's Gems: Extra Parts] (SGExtraParts-1.11-1.2.4-12.jar) 
	UCH	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCH	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCH	tammodized{0.6.2} [TamModized] (TamModized-1.11.2-0.6.2.jar) 
	UCH	techreborn{2.1.9.82} [TechReborn] (TechReborn-1.11.2-2.1.9.82-universal.jar) 
	UCH	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCH	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCH	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCH	voidcraft{0.17.7} [VoidCraft] (VoidCraft-1.11.2-0.17.7.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.6.26 mc1.11.2.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
  shetiphian.core.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.3.2.1.jar)
  
LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  lumien.randomthings.asm.ClassTransformer
ItemPatchingLoader (ItemPhysic Full 1.3.11 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
LoadingPlugin (HardcoreDarkness-MC1.11-1.8.1.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	List of loaded APIs: 
		* AbyssalCraftAPI (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Biome (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Block (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Disruption (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Energy (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Entity (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Event (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Integration (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Internal (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Item (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Necronomicon (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Recipe (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* AbyssalCraftAPI|Ritual (1.8.9) from AbyssalCraft-1.11.2-1.9.3.10.jar
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r103.jar
		* AdvInvAPI (1) from advInv-1.11.2-1.3.0.jar
		* ArmorPlusApi (2.0) from armorplus-1.11.2-10.1.2.3.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.3.12) from BetterAchievements-1.11.2-0.4.3.12.jar
		* bloodmagic|API (1.11-2.1.6-75) from BloodMagic-1.11-2.1.6-75.jar
		* BotaniaAPI (79) from AkashicTome-1.1-7.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from theoneprobe-1.1x-1.4.4.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.9.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.9.jar
		* compatlayer (0.2.2) from compatlayer-1.11.2-0.2.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.402.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.402.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.2.58.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.2.58.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (1.11-2.1.0-50) from Guide-API-1.11-2.1.0-50.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.9.247.jar
		* lightningcraftAPI (2.8.1) from lightningcraft-2.8.2-[1.11.2].jar
		* mcjtylib_ng (2.3.9) from mcjtylib-1.1x-2.3.9.jar
		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
		* reborncoreAPI (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Fuel (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Power (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Recipe (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Tile (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* SilentGemsAPI (2) from SilentsGems-1.11.x-2.3.1-140.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* techrebornAPI (2.1.9.82) from TechReborn-1.11.2-2.1.9.82-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.4.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* veinminerApi (0.3) from VeinMiner-1.11-0.35.3.605+dad98e1.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.4.37
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by SilentChaos512** [comment]
Looks like it just needs a clean build. It's trying to access the creative tabs in Silent's Gems, which changed a bit in recent versions.

**Comment by SilentChaos512** [comment]
Looks like it just needs a clean build. It's trying to access the creative tabs in Silent's Gems, which changed a bit in recent versions.
