### ISSUE TITLE
Recipies Don't Appear in JEI?

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/SGExtraParts#4]
Not seeing any recipes from the tools SGExtraParts adds. The normal recipes do show up from the main mod.

Using latest version of forge + JEI + all the SG mods.

**Comment by SilentChaos512** [comment]
This was a conscious decision, as adding even more "example recipes" felt unnecessary. Extra Parts uses the crafting mechanics of Silent's Gems tools. The same rules apply:
1. Tiers of the "main parts" (ingots, gems, etc.) must be the same.
2. The rod parts must support the tier of the mains.
3. Different mains can be mixed into a single tool (even mixing parts from different mods is OK).
4. Rod parts must be identical.

The tooltips added to the parts and the basic layout for the tool type are really all you need.
