### ISSUE TITLE
[1.11.2] Crash when opening inventory in creative

### ISSUE THREAD

**Issue by MasterEnderman** [SilentChaos512/SGExtraParts#5]
Every time i try to open my inventory in creative the game crashes. In the crash report it is says something about the material illuminite from netherrocks.

[Crash-Report](https://pastebin.com/XFhqQRuU)

forge: 13.20.0.2315
Silent Lib: 2.1.4-59
Silent Gems: 2.3.14-182
SG Extra Parts: 1.2.5-20
Netherrocks: 1.5.3.1

**Comment by SilentChaos512** [comment]
Looks like I have the spelling wrong. Not sure if it changed or what, but I can fix it.

**Comment by SilentChaos512** [comment]
Closed by 33a3ce4059b1a435f171a2ef34a99fb48047cfea
