### ISSUE TITLE
Just letting you know the Feldspar item texture seems to be missing. 

### ISSUE THREAD

**Issue by MCJediYoda** [SilentChaos512/SGExtraParts#6]
The Feldspar is missing item texture.  
SGExtraParts-1.12-1.3.1-25
Minecraft 1.10.2

**Comment by SilentChaos512** [comment]
Must be a 1.10.2-specific issue, everything shows up in 1.12. I'll take a look when I get the chance. Thanks for reporting this.

**Comment by nopun75** [comment]
Just wanted to bump this and say that the texture is missing in 1.11.2 as well with version 1.3.2-27 of the mod.

**Comment by SilentChaos512** [comment]
Finally got this figured out. Not entirely sure how I broke it. 1.12 changed when models are registered and I somehow removed/never had the compatibility code in place. Uploading fixed version now.
